(()=>{
const P=window.STC_PLAYERS, MAX=8, LAUNCH='2026-09-16';
const $=s=>document.querySelector(s), input=$('#guessInput'), suggestions=$('#suggestions'), rows=$('#rows'), form=$('#guessForm'), message=$('#message'), endPanel=$('#endPanel');
let mode='daily', answer=null, guesses=[], finished=false, selected=null, practiceId=0;
const DAY=86400000;
function norm(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function ordinal(n){const v=n%100;return n+(['th','st','nd','rd'][(v-20)%10]||['th','st','nd','rd'][v]||'th')}
function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function localMidnightMs(key){const [y,m,d]=key.split('-').map(Number);return new Date(y,m-1,d).getTime()}
function puzzleNumber(){return Math.floor((localMidnightMs(dateKey())-localMidnightMs(LAUNCH))/DAY)+1}
// Deterministic seeded permutation, so daily answers are stable and not dataset-order predictable.
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function mulberry32(a){return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
const shuffled=(()=>{const a=[...P],r=mulberry32(hash('STCdle-S1-S8-v1'));for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a})();
function dailyAnswer(){const n=Math.max(1,puzzleNumber());return shuffled[(n-1)%shuffled.length]}
function stateKey(){return `stcdle_daily_${dateKey()}`}
function loadDaily(){answer=dailyAnswer();const s=JSON.parse(localStorage.getItem(stateKey())||'null');guesses=s?.guesses?.map(id=>P.find(p=>p.id===id)).filter(Boolean)||[];finished=!!s?.finished;}
function saveDaily(){localStorage.setItem(stateKey(),JSON.stringify({guesses:guesses.map(g=>g.id),finished}))}
function randomPractice(){practiceId++;let next;do{next=P[Math.floor(Math.random()*P.length)]}while(P.length>1&&next?.id===answer?.id);answer=next;guesses=[];finished=false;selected=null;}
function compare(g){const sd=Math.abs(g.season-answer.season),pd=Math.abs(g.placement-answer.placement);return [
 [g.displayName,g.id===answer.id?'green':'gray'],
 [`S${g.season}${g.season===answer.season?'':answer.season>g.season?' ↑':' ↓'}`,sd===0?'green':sd===1?'yellow':'gray'],
 [`${ordinal(g.placement)}${g.placement===answer.placement?'':answer.placement<g.placement?' ↑':' ↓'}`,pd===0?'green':pd<=2?'yellow':'gray'],
 [g.gender,g.gender===answer.gender?'green':'gray'],[g.tribeColor,g.tribeColor===answer.tribeColor?'green':'gray'],[g.returnee?'Yes':'No',g.returnee===answer.returnee?'green':'gray']];}
function render(){rows.innerHTML='';guesses.forEach(g=>{const r=document.createElement('div');r.className='guess-row';compare(g).forEach(([t,c])=>{const d=document.createElement('div');d.className=`cell ${c}`;d.textContent=t;r.appendChild(d)});rows.appendChild(r)});for(let i=guesses.length;i<MAX;i++){const r=document.createElement('div');r.className='guess-row';for(let j=0;j<6;j++){const d=document.createElement('div');d.className='cell empty';r.appendChild(d)}rows.appendChild(r)}
 const won=guesses.at(-1)?.id===answer.id;$('#puzzleMeta').textContent=mode==='daily'?`STCdle #${Math.max(1,puzzleNumber())} · ${dateKey()}`:'Random practice puzzle';$('#modeDescription').textContent=mode==='daily'?'One castaway appearance. Eight guesses. Same puzzle for everyone today.':'Unlimited random puzzles. Practice games do not affect your streak.';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));input.disabled=finished;$('#guessBtn').disabled=finished;$('#newPracticeBtn').classList.toggle('hidden',mode!=='practice');
 if(finished){endPanel.classList.remove('hidden');$('#endTitle').textContent=won?'You survived!':'The tribe has spoken.';$('#endAnswer').innerHTML=`The answer was <strong>${answer.displayName}</strong> — ${ordinal(answer.placement)}, ${answer.startingTribe} (${answer.tribeColor}).`;$('#nextPuzzle').textContent=mode==='daily'?'Next daily puzzle arrives at local midnight.':'';}else endPanel.classList.add('hidden');
}
function showSuggestions(){const q=norm(input.value.trim());suggestions.innerHTML='';selected=null;if(!q){suggestions.classList.add('hidden');return}const used=new Set(guesses.map(g=>g.id));const hits=P.filter(p=>!used.has(p.id)&&norm(p.displayName).includes(q)).slice(0,12);if(!hits.length){suggestions.classList.add('hidden');return}hits.forEach(p=>{const b=document.createElement('button');b.type='button';b.className='suggestion';b.textContent=p.displayName;b.addEventListener('click',()=>{selected=p;input.value=p.displayName;suggestions.classList.add('hidden');input.focus()});suggestions.appendChild(b)});suggestions.classList.remove('hidden')}
function getStats(){return JSON.parse(localStorage.getItem('stcdle_stats_v1')||'{"played":0,"wins":0,"streak":0,"maxStreak":0,"lastCompleted":null,"distribution":[0,0,0,0,0,0,0,0]}')}
function updateStats(won){if(mode!=='daily')return;const today=dateKey(), s=getStats();if(s.lastCompleted===today)return;const yesterday=dateKey(new Date(Date.now()-DAY));s.played++;if(won){s.wins++;s.streak=s.lastCompleted===yesterday?s.streak+1:1;s.maxStreak=Math.max(s.maxStreak,s.streak);s.distribution[guesses.length-1]++}else s.streak=0;s.lastCompleted=today;localStorage.setItem('stcdle_stats_v1',JSON.stringify(s))}
function renderStats(){const s=getStats();$('#statPlayed').textContent=s.played;$('#statWin').textContent=s.played?Math.round(s.wins/s.played*100)+'%':'0%';$('#statStreak').textContent=s.streak;$('#statMax').textContent=s.maxStreak;const box=$('#distribution');box.innerHTML='';const max=Math.max(1,...s.distribution);s.distribution.forEach((n,i)=>{const r=document.createElement('div');r.className='dist-row';r.innerHTML=`<span>${i+1}</span><div class="dist-bar" style="width:${Math.max(8,n/max*100)}%">${n}</div>`;box.appendChild(r)})}
function emojiResult(){const won=guesses.at(-1)?.id===answer.id;const title=mode==='daily'?`STCdle #${Math.max(1,puzzleNumber())} ${won?guesses.length:'X'}/8`:`STCdle Practice ${won?guesses.length:'X'}/8`;const lines=guesses.map(g=>compare(g).map(([,c])=>c==='green'?'🟩':c==='yellow'?'🟨':'⬛').join(''));return `${title}\n\n${lines.join('\n')}`}
async function share(){const text=emojiResult();try{if(navigator.share)await navigator.share({text});else if(navigator.clipboard){await navigator.clipboard.writeText(text);message.textContent='Results copied to clipboard.'}else{window.prompt('Copy your results:',text)}}catch(e){if(e?.name!=='AbortError')window.prompt('Copy your results:',text)}}
form.addEventListener('submit',e=>{e.preventDefault();if(finished)return;let p=selected;const typed=norm(input.value.trim());if(!p)p=P.find(x=>norm(x.displayName)===typed);if(!p){message.textContent='Choose an appearance from the suggestions.';showSuggestions();return}if(guesses.some(g=>g.id===p.id)){message.textContent='You already guessed that appearance.';return}guesses.push(p);input.value='';selected=null;suggestions.classList.add('hidden');const won=p.id===answer.id;if(won||guesses.length===MAX){finished=true;updateStats(won)}if(mode==='daily')saveDaily();message.textContent='';render()});
input.addEventListener('input',showSuggestions);input.addEventListener('focus',showSuggestions);document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))suggestions.classList.add('hidden')});
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;message.textContent='';input.value='';if(mode==='daily')loadDaily();else randomPractice();render()}));
$('#newPracticeBtn').addEventListener('click',()=>{randomPractice();render();input.focus()});$('#shareBtn').addEventListener('click',share);$('#helpBtn').addEventListener('click',()=>$('#helpDialog').showModal());$('#statsBtn').addEventListener('click',()=>{renderStats();$('#statsDialog').showModal()});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).close()));
loadDaily();render();
})();
