// STCdle canonical player-appearance database: Seasons 1–8 only.
// Each returnee appearance is a separate guessable entry.
const STC_RAW = {
1:[['Vijaya Gopalan',1,'F','Real Hot and Sexy','Blue'],['Anna Sullivan',2,'F','Real Hot and Sexy','Blue'],['Ryan Seaver',3,'M','Real Hot and Sexy','Blue'],['Anne Kolstad',4,'F','Cuyuna','Red'],['Rachel Eyre',5,'F','Real Hot and Sexy','Blue'],['Tyler Karle',6,'M','Cuyuna','Red'],['Josie Machalek',7,'F','Real Hot and Sexy','Blue'],['Peter Lark',8,'M','Real Hot and Sexy','Blue'],['Bennett Sherwood',9,'M','Cuyuna','Red'],['Zack Hansen',10,'M','Cuyuna','Red'],['Truong Vu',11,'M','Cuyuna','Red'],['Abby Bennett',12,'F','Cuyuna','Red'],['Jason Martin',13,'M','Real Hot and Sexy','Blue'],['Ben Ray',14,'M','Real Hot and Sexy','Blue'],['Lucas Dahl',15,'M','Cuyuna','Red'],['Lena Pak',16,'F','Cuyuna','Red']],
2:[['Cade Nelson',1,'M','Wasaka','Blue'],['Luke Miller',2,'M','HotBishes','Black'],['Ashley McCann',3,'F','HotBishes','Black'],['Aidan Kadid',4,'M','Wasaka','Blue'],['Logan Lestina',5,'M','HotBishes','Black'],['Leo Newman',6,'M','Wasaka','Blue'],['Yana King',7,'F','Wasaka','Blue'],['Gaby Gutenkauf',8,'F','Wasaka','Blue'],['Sam Ahmed',9,'M','Wasaka','Blue'],['Cameron Tredal',10,'M','HotBishes','Black'],['Alexandra Holthaus',11,'F','HotBishes','Black'],['Meghan Durre',12,'F','HotBishes','Black'],['Ian Malis',13,'M','HotBishes','Black'],['Melanie Hernandez',14,'F','Wasaka','Blue']],
3:[['Alexandra Aker',1,'F','Vacca','Green'],['Grace Haverkampf',2,'F','Apili','Orange'],['Jacob Grzesiak',3,'M','Vacca','Green'],["Jack O'Connell",4,'M','Vacca','Green'],['Eli Klawikowski',5,'M','Apili','Orange'],['Griffin Jones',6,'M','Vacca','Green'],['Rakesh Plantz',7,'M','Vacca','Green'],['Selam Bushen',8,'F','Apili','Orange'],['Viola Lindell',9,'F','Apili','Orange'],['Luis Barrientos Muñoz',10,'M','Vacca','Green'],['Lauren Steenberg',11,'F','Apili','Orange'],['Deidra Meyer',12,'F','Vacca','Green'],['Dylan McKenzie',13,'F','Apili','Orange'],['Zachariah Becker',14,'M','Vacca','Green'],['Crow Wilkins',15,'F','Apili','Orange'],['Alec Zadra',16,'M','Apili','Orange']],
4:[['Rachel Laws',1,'F','Zorro','Blue'],['Ryder James',2,'M','Zorro','Blue'],['Tyler Wyninger',3,'M','Zorro','Blue'],['Tyris Lee',4,'M','Zorro','Blue'],['Karen Ugwu',5,'F','Adelaar','Yellow'],['Louie Bonnabeau',6,'M','Zorro','Blue'],['Hunter Mohs',7,'M','Adelaar','Yellow'],['Julia Miller',8,'F','Adelaar','Yellow'],['Kyle Jackson',9,'M','Adelaar','Yellow'],['Leon Savage',10,'M','Adelaar','Yellow'],['Emma Vasa',11,'F','Adelaar','Yellow'],['Megan Pangier',12,'F','Zorro','Blue'],['Shoshana Prager',13,'F','Adelaar','Yellow'],["Ainsley O'Higgins",14,'F','Zorro','Blue'],['Eli Hanson',15,'M','Adelaar','Yellow'],['Izzy Calhoon',16,'F','Zorro','Blue']],
5:[['Ricardo Vazquez Montero',1,'M','Drakon','Orange'],['Julia Faig',2,'F','Gula','Black'],['G Xiong',3,'F','Gula','Black'],['Sean Fahey',4,'M','Ligo','Purple'],['Seth Delikowski',5,'M','Ligo','Purple'],['Lindsey Williams',6,'F','Gula','Black'],['Jack Bellinger',7,'M','Gula','Black'],['Chloe McCormick',8,'F','Drakon','Orange'],['Ella Johnson',9,'F','Drakon','Orange'],['Rocco Ruggeri',10,'M','Drakon','Orange'],['Rylie Saloum',11,'F','Ligo','Purple'],['Jalesheah Simpson',12,'F','Drakon','Orange'],['Gabriela Oconitrillo',13,'F','Ligo','Purple'],['Mikhail Thompson',14,'M','Ligo','Purple'],['Lexi Strickland',15,'F','Ligo','Purple'],['Keegan Hennessey',16,'M','Gula','Black'],['Aidan Zhuelke',17,'M','Drakon','Orange'],['Yikai Zhang',18,'M','Gula','Black']],
6:[['Julia Miller',1,'F','Lanakila','Orange'],['Luke Miller',2,'M','Manumalo','Green'],['Julia Faig',3,'F','Lanakila','Orange'],['Tyler Wyninger',4,'M','Manumalo','Green'],['Yana King',5,'F','Lanakila','Orange'],['Anna Sullivan',6,'F','Manumalo','Green'],['Louie Bonnabeau',7,'M','Lanakila','Orange'],['Logan Lestina',8,'M','Manumalo','Green'],['Cade Nelson',9,'M','Lanakila','Orange'],["Jack O'Connell",10,'M','Lanakila','Orange'],['Ricardo Vazquez Montero',11,'M','Manumalo','Green'],['Alexandra Aker',12,'F','Manumalo','Green'],['G Xiong',13,'F','Manumalo','Green'],['Leon Savage',14,'M','Lanakila','Orange'],['Truong Vu',15,'M','Manumalo','Green'],['Tyler Karle',16,'M','Lanakila','Orange'],['Emma Vasa',17,'F','Manumalo','Green'],['Mikhail Thompson',18,'M','Lanakila','Orange']],
7:[['Sydney Amundson',1,'F','Bennu','Black'],['Ethan Fizel',2,'M','Bennu','Black'],['Sophia Aschoff',3,'F','Bennu','Black'],['Ryan Klima',4,'M','Bennu','Black'],['Nadia Bierbaum',5,'F','Kavma','Red'],['Crystal Kastenholz',6,'F','Bennu','Black'],['Colin Nettesheim',7,'M','Bennu','Black'],['Daigan Berger',8,'M','Kavma','Red'],['Nick Bealke',9,'M','Kavma','Red'],['Jace Bancroft',10,'M','Bennu','Black'],['Quinn Syed',11,'M','Kavma','Red'],['Madilyn Salveson',12,'F','Kavma','Red'],['Bridget Reilly',13,'F','Kavma','Red'],['Kaitlyn Sawyers',14,'F','Kavma','Red'],['Ela Gutierrez',15,'F','Bennu','Black'],['KK Kasouaher',16,'M','Bennu','Black'],['Ethan Kraayeveld',17,'M','Kavma','Red'],['Kada Jackson',18,'F','Kavma','Red']],
8:[['Jack Bellinger',1,'M','Sanguis','Blue'],['Kate Abelson',2,'F','Vulnus','Purple'],['Olivia Cooper',3,'F','Vulnus','Purple'],['Rakesh Plantz',4,'M','Sanguis','Blue'],['Ryder James',5,'M','Sanguis','Blue'],['Alex Nuñez',6,'M','Vulnus','Purple'],['Rachel Laws',7,'F','Sanguis','Blue'],['Kay Ewald',8,'F','Vulnus','Purple'],['Ella Johnson',9,'F','Sanguis','Blue'],['Tyler Guenin',10,'M','Vulnus','Purple'],['Noah Winters',11,'M','Vulnus','Purple'],['Sydney Amundson',12,'F','Sanguis','Blue'],['Viola Lindell',13,'F','Sanguis','Blue'],['Brooke Koebel',14,'F','Vulnus','Purple'],['Lily Espinoza',15,'F','Vulnus','Purple'],['Deidra Meyer',16,'F','Sanguis','Blue'],['Andrés Roman Comas-Wood',17,'M','Vulnus','Purple'],['Nick Bealke',18,'M','Sanguis','Blue'],['Matt Trussell',19,'M','Vulnus','Purple'],['Hunter Mohs',20,'M','Sanguis','Blue']]
};

function stcSlug(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
window.STC_PLAYERS=[];
Object.entries(STC_RAW).forEach(([season,rows])=>rows.forEach(r=>window.STC_PLAYERS.push({
  id:`${stcSlug(r[0])}_s${season}`, name:r[0], displayName:`${r[0]} (Season ${season})`, season:+season,
  placement:r[1], gender:r[2], startingTribe:r[3], tribeColor:r[4],
  returnee:+season===6 || (+season===8 && r[3]==='Sanguis')
})));
